### ISSUE TITLE
Unexpected task(priority:) Availability Error on macOS 15+ Deployment Target

### ISSUE THREAD

**Issue by sharukmsd** [baskurthalit/asyncImage#2]
**Environment:**
- macOS Deployment Target: 15.0 or newer
- iOS Deployment Target: 13.0 or newer
- SwiftUI project targeting iOS and macOS

**Problem:** When using CAsyncImage in a SwiftUI project with a deployment target of macOS 15.0 or newer, the `.task(priority:)` modifier throws an error indicating that it is "only available in macOS 12.0 or newer." The error message displayed is:

`task(priority:)' is only available in macOS 12.0 or newer`

This error occurs despite the project and system both targeting and running on macOS 15.0 or newer.

`Steps to Reproduce:`
- Set the deployment target of your SwiftUI project to macOS 15.0 or newer.
- Use the CAsyncImage in a SwiftUI view to load an image asynchronously.
- Attempt to build the project for macOS.

<img width="1792" alt="Screenshot 2024-11-09 at 2 46 11 PM" src="https://github.com/user-attachments/assets/30c62bfb-e0a1-41fa-a178-28d4e41a6295">

**Comment by baskurthalit** [comment]
> **Environment:**
> 
> * macOS Deployment Target: 15.0 or newer
> * iOS Deployment Target: 13.0 or newer
> * SwiftUI project targeting iOS and macOS
> 
> **Problem:** When using CAsyncImage in a SwiftUI project with a deployment target of macOS 15.0 or newer, the `.task(priority:)` modifier throws an error indicating that it is "only available in macOS 12.0 or newer." The error message displayed is:
> 
> `task(priority:)' is only available in macOS 12.0 or newer`
> 
> This error occurs despite the project and system both targeting and running on macOS 15.0 or newer.
> 
> `Steps to Reproduce:`
> 
> * Set the deployment target of your SwiftUI project to macOS 15.0 or newer.
> * Use the CAsyncImage in a SwiftUI view to load an image asynchronously.
> * Attempt to build the project for macOS.
> 
> <img alt="Screenshot 2024-11-09 at 2 46 11 PM" width="1792" src="https://private-user-images.githubusercontent.com/47911050/384597486-30c62bfb-e0a1-41fa-a178-28d4e41a6295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNTA2NTAsIm5iZiI6MTczMTE1MDM1MCwicGF0aCI6Ii80NzkxMTA1MC8zODQ1OTc0ODYtMzBjNjJiZmItZTBhMS00MWZhLWExNzgtMjhkNGU0MWE2Mjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDExMDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYjBiZDlkYjI3N2E0ZTNjNDgzZmQzMmJmZjgzODVmNTI5MDc2N2M3ZmM3NjkzYTAxMGUyYjFjNmQxMDBmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fvwon3jtuns_Rk182kSCu7qsOgXTqVD-aQyIH0rt-6o">

Hi, sharukmsd

Thank you for your interest and letting me know. I tried and encountered with the same problem. It seems like I forget to add device check for there. 

I saw your contribution and will review and merge.

- Halit
